name: Auto Sync with Upstream

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

env:
  UPSTREAM_REPO: "git@github.com:Tencent/vap.git"
  TARGET_BRANCH: "master"

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Random Sleep
        run: |
          MINUTES=$(( $RANDOM % 361 ))
          echo "Sleeping for $MINUTES minutes..."
          sleep $((MINUTES * 60))

      - name: Checkout fork repo
        uses: actions/checkout@v3
        with:
          ref: main
          persist-credentials: false

      - name: Set git config
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
      
      - name: Add upstream
        run: git remote add upstream ${{ env.UPSTREAM_REPO }}

      - name: Fetch upstream
        run: git fetch upstream

      - name: Merge upstream brance
        run: git merge upstream/${{ env.TARGET_BRANCH }} --allow-unrelated-histories

      - name: Push changes
        run: git push origin ${{ env.TARGET_BRANCH }}
        env:
          TOKEN: ${{ secrets.GITHUB_TOKEN }}